name: Branch Check

on:
  pull_request:
    branches:
      - main
      - master

jobs:
  check-branch:
    runs-on: ubuntu-latest
    steps:
    - name: Check Source Branch
      run: |
        if [[ "${{ github.base_ref }}" == "master" && "${{ github.head_ref }}" != "development" ]]; then
          echo "Error: PRs to 'main' must come from 'development' branch."
          exit 1
        fi
